### ISSUE TITLE
Graph combines test and app packages into a single package

### ISSUE THREAD

**Issue by dmitri-minkin** [tricycle/graphwerk#9]
Graphwerk combines both app/games and spec/games package into single package: package/games.

I used the same directory structure and ran both graphwerk and pocky on the same folder which gave different results.
I think graphwerk has a bug.

Directory structure:

```
sportsball
 |- app
     |-packages
         |- games
              |- package.yml
         ... etc
 |- spec
     |-packages
         |- games
              |- package.yml
         ... etc
```

Notice that test (spec) package depends on the appropriate app package, that is spec/games depends on app/games:

in sportsball/spec/packages/games/package.yml :
```
enforce_dependencies: true
enforce_privacy: false
dependencies:
  - app/packages/games
```

But on diagram we get single package package/games that references itself which is wrong.
Basically graphwerk combined both app/games and spec/games package into single package: package/games

# Additional info

in sportsball/app/packages/games/package.yml :
```
enforce_dependencies: true
enforce_privacy: false
dependencies:
  - app/packages/rails_shims
  - app/packages/teams
```

the only deprecated_references.yml file is under root:
 sportsball/deprecated_references.yml
```
# This file contains a list of dependencies that are not part of the long term plan for ..
# We should generally work to reduce this list, but not at the expense of actually getting work done.
#
# You can regenerate this file using the following command:
#
# bin/packwerk update-deprecations .
---
app/packages/games:
  "::Game":
    violations:
    - dependency
    files:
    - spec/support/object_creation_methods.rb
app/packages/teams:
  "::Team":
    violations:
    - dependency
    files:
    - spec/support/object_creation_methods.rb
```

Graphwerk result of running:
`bundle exec rake graphwerk:update `

![packwerk.png](https://user-images.githubusercontent.com/73537462/180041908-6de873c5-bbb7-49aa-84c0-aefbe38f59d3.png)

Pocky result of running:
`rake pocky:generate"[root]" `
![packwerk.png](https://user-images.githubusercontent.com/73537462/180042224-e31b4c61-178b-4aae-b2c6-275e9a92842d.png)
